### ISSUE TITLE
入出力ファイルの形式変更

### ISSUE THREAD

**Issue by MarikoOhtsuka** [nnh/ptosh-csv#1]
入力はcp932->utf-8-bomに変更
出力はcp932を明示するように変更

**Comment by MarikoOhtsuka** [comment]
入出力ともにcp932->utf-8-bomに変更
Windows端末のExcelで出力ファイルのオープンテストを実施する

**Comment by tosh13** [comment]
ありがとうございます。CP932, Shift-JISは可能な限り駆逐して下さい。
